//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wp7_api_demos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wp7_api_demos.Resources.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://cloud.mobeelizer.com/sync/v2/.
        /// </summary>
        internal static string c_apiURL_host {
            get {
                return ResourceManager.GetString("c_apiURL_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /demos/create.
        /// </summary>
        internal static string c_apiURL_path {
            get {
                return ResourceManager.GetString("c_apiURL_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string c_userALogin {
            get {
                return ResourceManager.GetString("c_userALogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Su(w4KV4L.
        /// </summary>
        internal static string c_userAPassword {
            get {
                return ResourceManager.GetString("c_userAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string c_userBLogin {
            get {
                return ResourceManager.GetString("c_userBLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B9$zGOl6!n.
        /// </summary>
        internal static string c_userBPassword {
            get {
                return ResourceManager.GetString("c_userBPassword", resourceCulture);
            }
        }
    }
}
