//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wp7_api_demos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wp7_api_demos.Resources.ResourceDictionary", typeof(ResourceDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string connectButton {
            get {
                return ResourceManager.GetString("connectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining session.
        /// </summary>
        public static string connectingProgressMessage {
            get {
                return ResourceManager.GetString("connectingProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string createButton {
            get {
                return ResourceManager.GetString("createButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new demo session:.
        /// </summary>
        public static string createDemoSessionInfo {
            get {
                return ResourceManager.GetString("createDemoSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or connect to an existing one.
        /// </summary>
        public static string createDemoSessionInfo2 {
            get {
                return ResourceManager.GetString("createDemoSessionInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two users modify one record at the same time? You can easily cope with that!.
        /// </summary>
        public static string dialogConflictsSyncText1 {
            get {
                return ResourceManager.GetString("dialogConflictsSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one movie title that all users have. Now change movie rating and synchronize updated data….
        /// </summary>
        public static string dialogConflictsSyncText2 {
            get {
                return ResourceManager.GetString("dialogConflictsSyncText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the same record with another user and then synchronize….
        /// </summary>
        public static string dialogConflictsSyncText3 {
            get {
                return ResourceManager.GetString("dialogConflictsSyncText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And… don&apos;t worry anymore. No data is lost! Your record is in conflict state, but it&apos;s easy to resolve it - although not in this demo….
        /// </summary>
        public static string dialogConflictsSyncText4 {
            get {
                return ResourceManager.GetString("dialogConflictsSyncText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, conflicts arise….
        /// </summary>
        public static string dialogConflictsSyncTitle {
            get {
                return ResourceManager.GetString("dialogConflictsSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new images   .
        /// </summary>
        public static string dialogFilesSyncAddText {
            get {
                return ResourceManager.GetString("dialogFilesSyncAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out how easy data exchange can be!.
        /// </summary>
        public static string dialogFilesSyncText1 {
            get {
                return ResourceManager.GetString("dialogFilesSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also simple way to share binaries….
        /// </summary>
        public static string dialogFilesSyncTitle {
            get {
                return ResourceManager.GetString("dialogFilesSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new elements.
        /// </summary>
        public static string dialogInfoAddText {
            get {
                return ResourceManager.GetString("dialogInfoAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now switch user or connect another device.
        /// </summary>
        public static string dialogInfoChengeUserText {
            get {
                return ResourceManager.GetString("dialogInfoChengeUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize added elements with the cloud.
        /// </summary>
        public static string dialogInfoSyncText1 {
            get {
                return ResourceManager.GetString("dialogInfoSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync to see new elements.
        /// </summary>
        public static string dialogInfoSyncText2 {
            get {
                return ResourceManager.GetString("dialogInfoSyncText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, sync, switch user, sync….
        /// </summary>
        public static string dialogInfoSyncText3 {
            get {
                return ResourceManager.GetString("dialogInfoSyncText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But do not sync data yet!.
        /// </summary>
        public static string dialogInfoSyncText4 {
            get {
                return ResourceManager.GetString("dialogInfoSyncText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your app you can easily define who will see what..
        /// </summary>
        public static string dialogPermissionsSyncText1 {
            get {
                return ResourceManager.GetString("dialogPermissionsSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See difference? That&apos;s right! Some data are accesible only to creator, some to everyone. But you can do so much more….
        /// </summary>
        public static string dialogPermissionsSyncText2 {
            get {
                return ResourceManager.GetString("dialogPermissionsSyncText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your shared data….
        /// </summary>
        public static string dialogPermissionsSyncTitle {
            get {
                return ResourceManager.GetString("dialogPermissionsSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can simply send push notifications without thinking about operating systems and devices..
        /// </summary>
        public static string dialogPushNotificationsText1 {
            get {
                return ResourceManager.GetString("dialogPushNotificationsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also you can specify receiver of your notification. He will get it - on every device he&apos;s logged in (even if application is turned off)..
        /// </summary>
        public static string dialogPushNotificationsText2 {
            get {
                return ResourceManager.GetString("dialogPushNotificationsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify users with minimum effort….
        /// </summary>
        public static string dialogPushNotificationsTitle {
            get {
                return ResourceManager.GetString("dialogPushNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how users can interfere with each other working on common Orders..
        /// </summary>
        public static string dialogRelationConflictsSyncText1 {
            get {
                return ResourceManager.GetString("dialogRelationConflictsSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As in previous example - choose one order and change it&apos;s status, synchronize data….
        /// </summary>
        public static string dialogRelationConflictsSyncText2 {
            get {
                return ResourceManager.GetString("dialogRelationConflictsSyncText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now using another user add or remove position in previously choosen order. Synchronize data..
        /// </summary>
        public static string dialogRelationConflictsSyncText3 {
            get {
                return ResourceManager.GetString("dialogRelationConflictsSyncText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t be afraid. Your orders are secure. Conflicts can also occour in more complicated structures - like orders and positions. Of course you can feel safe, we will handle them for you….
        /// </summary>
        public static string dialogRelationConflictsSyncText4 {
            get {
                return ResourceManager.GetString("dialogRelationConflictsSyncText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations, conflicts - no problem at all….
        /// </summary>
        public static string dialogRelationConflictsSyncTitle {
            get {
                return ResourceManager.GetString("dialogRelationConflictsSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange simple data between users..
        /// </summary>
        public static string dialogSimpleSyncText1 {
            get {
                return ResourceManager.GetString("dialogSimpleSyncText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it&apos;s your turn! Try to add more records and exchange them between as many devices and users as you can find….
        /// </summary>
        public static string dialogSimpleSyncText2 {
            get {
                return ResourceManager.GetString("dialogSimpleSyncText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple way to share data….
        /// </summary>
        public static string dialogSimpleSyncTitle {
            get {
                return ResourceManager.GetString("dialogSimpleSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items marked with     were not synchronized, because other user edited them at the same time..
        /// </summary>
        public static string footerWarning {
            get {
                return ResourceManager.GetString("footerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mobeelizer.com/.
        /// </summary>
        public static string gettingStartedLink {
            get {
                return ResourceManager.GetString("gettingStartedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string gettingStartedLinkText {
            get {
                return ResourceManager.GetString("gettingStartedLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobeelizer.com.
        /// </summary>
        public static string gettingStartedLinkText1 {
            get {
                return ResourceManager.GetString("gettingStartedLinkText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for more info..
        /// </summary>
        public static string gettingStartedLinkText2 {
            get {
                return ResourceManager.GetString("gettingStartedLinkText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobeelizer is a Synchronization-as-a-Service for mobile developers. We strive to make it ridiculously easy to get synchronization for mobile apps up and running, so you can focus on creating mobile apps, without worrying about data exchange..
        /// </summary>
        public static string gettingStartedText {
            get {
                return ResourceManager.GetString("gettingStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using Mobeelizer, we automatically take care about the backend, configuration and complicated aspect of synchronization conflicts..
        /// </summary>
        public static string gettingStartedText1 {
            get {
                return ResourceManager.GetString("gettingStartedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app contains examples of using mobeelizer in different scenarios. You can see how to sync data, binary files or how to handle conflicts. It&apos;s only a small possibilities what mobeelizer can do for you. So have fun!.
        /// </summary>
        public static string gettingStartedText3 {
            get {
                return ResourceManager.GetString("gettingStartedText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string graphsDetailsNew {
            get {
                return ResourceManager.GetString("graphsDetailsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string graphsDetailsPending {
            get {
                return ResourceManager.GetString("graphsDetailsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to ship.
        /// </summary>
        public static string graphsDetailsReady {
            get {
                return ResourceManager.GetString("graphsDetailsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string graphsDetailsReceived {
            get {
                return ResourceManager.GetString("graphsDetailsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string graphsDetailsShipped {
            get {
                return ResourceManager.GetString("graphsDetailsShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string m_about {
            get {
                return ResourceManager.GetString("m_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts.
        /// </summary>
        public static string m_conflicts {
            get {
                return ResourceManager.GetString("m_conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string m_files {
            get {
                return ResourceManager.GetString("m_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string m_permisions {
            get {
                return ResourceManager.GetString("m_permisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications.
        /// </summary>
        public static string m_push {
            get {
                return ResourceManager.GetString("m_push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Conflicts.
        /// </summary>
        public static string m_relations {
            get {
                return ResourceManager.GetString("m_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Sync.
        /// </summary>
        public static string m_sync {
            get {
                return ResourceManager.GetString("m_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do next?.
        /// </summary>
        public static string m_whatNext {
            get {
                return ResourceManager.GetString("m_whatNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;movies&gt;
        ///    &lt;movieTitles&gt;
        ///        &lt;item&gt;The Shawshank Redemption&lt;/item&gt;
        ///        &lt;item&gt;The Godfather&lt;/item&gt;
        ///        &lt;item&gt;The Godfather: Part II&lt;/item&gt;
        ///        &lt;item&gt;Pulp Fiction&lt;/item&gt;
        ///        &lt;item&gt;Il buono, il brutto, il cattivo.&lt;/item&gt;
        ///        &lt;item&gt;12 Angry Men&lt;/item&gt;
        ///        &lt;item&gt;Schindler’s List&lt;/item&gt;
        ///        &lt;item&gt;The Dark Knight&lt;/item&gt;
        ///        &lt;item&gt;The Lord of the Rings: The Return of the King&lt;/item&gt;
        ///        &lt;item&gt;One Flew Over the Cuckoo’s Nest&lt;/item&gt;
        ///        &lt;item&gt;Star Wars: Episod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect other device to this session insert code: .
        /// </summary>
        public static string sessionInfo {
            get {
                return ResourceManager.GetString("sessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on startup screen..
        /// </summary>
        public static string sessionInfo2 {
            get {
                return ResourceManager.GetString("sessionInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that on each connected device you can be logged as one of two users. To switch user simply press one of two user buttons placed on top of the screen..
        /// </summary>
        public static string sessionInfo3 {
            get {
                return ResourceManager.GetString("sessionInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you&apos;ve seen how revolutionary mobeelizer is and what Synchronization-as-a-Service means for your app..
        /// </summary>
        public static string whatNextText {
            get {
                return ResourceManager.GetString("whatNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it&apos;s time for you to code&amp;play with mobeelizer by yourself..
        /// </summary>
        public static string whatNextText1 {
            get {
                return ResourceManager.GetString("whatNextText1", resourceCulture);
            }
        }
    }
}
