//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wp7_api_demos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wp7_api_demos.Resources.ResourceDictionary", typeof(ResourceDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string m_about {
            get {
                return ResourceManager.GetString("m_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts.
        /// </summary>
        internal static string m_conflicts {
            get {
                return ResourceManager.GetString("m_conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string m_files {
            get {
                return ResourceManager.GetString("m_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string m_permisions {
            get {
                return ResourceManager.GetString("m_permisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications.
        /// </summary>
        internal static string m_push {
            get {
                return ResourceManager.GetString("m_push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Conflicts.
        /// </summary>
        internal static string m_relations {
            get {
                return ResourceManager.GetString("m_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Sync.
        /// </summary>
        internal static string m_sync {
            get {
                return ResourceManager.GetString("m_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do next?.
        /// </summary>
        internal static string m_whatNext {
            get {
                return ResourceManager.GetString("m_whatNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;movies&gt;
        ///	&lt;movie director=&quot;&quot; title&quot;&quot;/&gt;
        ///&lt;/movies&gt;.
        /// </summary>
        internal static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
    }
}
